# Generated by Django 4.2.2 on 2023-06-06 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planApp1', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ausbilungsberuf',
            name='beschreibung',
            field=models.TextField(blank=True, verbose_name='Beschreibung'),
        ),
    ]
