# Generated by Django 4.2.2 on 2023-06-06 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planApp1', '0002_alter_ausbilungsberuf_beschreibung'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Ausbilungsberuf',
            new_name='Ausbildungsberuf',
        ),
        migrations.AlterModelOptions(
            name='ausbildungsberuf',
            options={'verbose_name': 'Ausbildungsberuf', 'verbose_name_plural': 'Ausbildungsberufe'},
        ),
        migrations.AddField(
            model_name='lernfeld',
            name='berufe',
            field=models.ManyToManyField(to='planApp1.ausbildungsberuf', verbose_name='Berufe'),
        ),
    ]
