# Generated by Django 4.2.2 on 2023-06-06 16:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('planApp1', '0004_alter_lernfeld_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Schlagwort',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Schlagwort')),
            ],
            options={
                'verbose_name': 'Schlagwort',
                'verbose_name_plural': 'Schlagwörter',
                'ordering': ['name'],
            },
        ),
        migrations.AlterModelOptions(
            name='lernfeld',
            options={'ordering': ['name'], 'verbose_name': 'Lernfeld', 'verbose_name_plural': 'Lernfelder'},
        ),
        migrations.CreateModel(
            name='Lernbaustein',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nummer', models.CharField(max_length=10, verbose_name='Nummer')),
                ('beschreibung', models.TextField(verbose_name='Beschreibung')),
                ('lernfeld', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='planApp1.lernfeld', verbose_name='Lernfeld')),
                ('schlagwoerter', models.ManyToManyField(to='planApp1.schlagwort', verbose_name='Schlagwörter')),
            ],
            options={
                'verbose_name': 'Lernbaustein',
                'verbose_name_plural': 'Lernbausteine',
            },
        ),
    ]
