# Generated by Django 4.2.2 on 2023-06-06 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planApp1', '0006_alter_lernbaustein_options_lernbaustein_stunden'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lernbaustein',
            name='stunden',
            field=models.IntegerField(default=0, verbose_name='Stunden'),
        ),
        migrations.AlterField(
            model_name='schlagwort',
            name='name',
            field=models.CharField(max_length=50, unique=True, verbose_name='Schlagwort'),
        ),
    ]
