# Generated by Django 4.2.2 on 2023-06-07 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planApp1', '0007_alter_lernbaustein_stunden_alter_schlagwort_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sequenz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
                ('bemerkung', models.TextField(verbose_name='Eräuterungen')),
                ('stunden', models.IntegerField(verbose_name='Geplante Stunden')),
                ('lernbausteine', models.ManyToManyField(to='planApp1.lernbaustein', verbose_name='Lernbausteine')),
            ],
            options={
                'verbose_name': 'Sequenz',
                'verbose_name_plural': 'Sequenzen',
            },
        ),
    ]
