# Generated by Django 4.2.2 on 2023-06-08 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planApp1', '0008_sequenz'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mitarbeiter',
            fields=[
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('kuerzel', models.CharField(max_length=10, primary_key=True, serialize=False, verbose_name='Kürzel')),
            ],
            options={
                'verbose_name': 'Mitarbeiter',
                'verbose_name_plural': 'Mitarbeiter',
            },
        ),
    ]
