# Generated by Django 4.2.2 on 2023-06-08 16:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('planApp1', '0009_mitarbeiter'),
    ]

    operations = [
        migrations.AddField(
            model_name='sequenz',
            name='mitarbeiter',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='planApp1.mitarbeiter', verbose_name='Mitarbeiter'),
        ),
    ]
